apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  # list of containers
  containers:
  - name: debug
    image: 484907532817.dkr.ecr.us-east-1.amazonaws.com/roboshop/debug:v1.5
    # image: lingadevops/debug:v1.1
    #here with this line port will not be opened, just for information
    command: ["sleep", "100000"]