apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: roboshop
  labels: # these labels are deployment labels
    app: dispatch
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: dispatch
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: dispatch
        project: roboshop
        tier: db
    spec:
      containers:
      - name: dispatch
        image: 484907532817.dkr.ecr.us-east-1.amazonaws.com/roboshop/dispatch:v1.5
        # image: lingadevops/dispatch:v1.1
        # imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
  namespace: roboshop
spec:
  selector:
    app: dispatch
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port
